# Generated by Django 3.2.12 on 2022-02-02 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('section_description', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_section', to='nesting_books.book')),
                ('parent_section', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='nesting_books.booksection')),
            ],
        ),
    ]
